version: "3"
services:
  application:
    build: container
    image: naruhito/ubuntu-xrdp:22.04
    container_name: ubuntu-xrdp
    hostname: ubuntu-xrdp
    restart: always
    ports:
      - "13389:3389"
      - "10022:22"
    # security_opt:  # NOTE: https://www.creationline.com/lab/46861
    #   - "seccomp:unconfined"  # sudo yum install libseccomp OR sudo apt install libseccomp-dev
